#!/bin/sh
SERVICE_NAME=SecurityService
PATH_TO_JAR=Authentication-service-0.0.1-SNAPSHOT.jar
PID_PATH_NAME=/TMP/MyService-pid
case $1 in
       start)
	     echo "Starting $SERVICE_NAME ..."
	     if [ ! -f $PID_PATH_NAME ]; then 
	       nohup java -jar $PATH_TO_JAR /tmp 2>> /dev/null & echo $! > $PID_PATH_NAME
		   echo "$SERVICE_NAME started ..."
	     else 
	       echo "$SERVICE_NAME is already running ..."
	     fi
	   ;;
	   stop)
	     if [ -f $PID_PATH_NAME ]; then
	        PID=$(cat $PID_PATH_NAME);
			echo "$SERVICE_NAME stoping ..."
			kill $PID;
			echo "$SERVICE_NAME stopped ..."
			rm $PID_PATH_NAME
		 else
		    echo "$SERVICE_NAME is not running ..."
		 fi
		;;
		restart)
		   if [ -f $PID_PATH_NAME ]; then
	        PID=$(cat $PID_PATH_NAME);
			echo "$SERVICE_NAME stoping ..."
			kill $PID;
			echo "$SERVICE_NAME stopped ..."
			rm $PID_PATH_NAME
			echo "$SERVICE_NAME Starting ..."
			nohup java -jar $PATH_TO_JAR /tmp 2>> /dev/null >> /dev/null echo $! > $PID_PATH_NAME
			echo "$SERVICE_NAME started ..."
		  else
		    echo "$SERVICE_NAME is not running ..."
		  fi
		;;
esac
		 
